version: '3'

datasources:
  - name: 'InfluxDB'
    type: 'influxdb'
    access: 'proxy'
    url: 'http://influxdb:8086'
    database: 'ectc_data'
    isDefault: true

  - name: 'Prometheus'
    type: 'prometheus'
    access: 'proxy'
    url: 'http://prometheus:9090'
    isDefault: false

apiVersion: 1

providers:
  - name: 'default'
    orgId: 1
    folder: ''
    type: file
    disableDeletion: false
    options:
      path: /var/lib/grafana/dashboards
